<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="Akash" failures="1" tests="5" name="MyTest" time="0.042" errors="0" timestamp="2022-04-14T11:27:00 IST">
  <testcase classname="test.TestNgHook" name="test2" time="0.005"/>
  <testcase classname="test.TestNgHook" name="test1" time="0.007"/>
  <testcase classname="test.ProductServiceTest" name="storeProductTest" time="0.01"/>
  <testcase classname="test.ProductServiceTest" name="findProductTest" time="0.01"/>
  <testcase classname="test.OperationTest" name="testAdd" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [70] but found [30]">
      <![CDATA[java.lang.AssertionError: expected [70] but found [30]
at test.OperationTest.testAdd(OperationTest.java:14)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testAdd -->
  <testcase classname="test.OperationTest" name="testDiv" time="0.0">
    <ignored/>
  </testcase> <!-- testDiv -->
  <testcase classname="test.OperationTest" name="testSub" time="0.0">
    <ignored/>
  </testcase> <!-- testSub -->
  <testcase classname="test.OperationTest" name="testMult" time="0.0">
    <ignored/>
  </testcase> <!-- testMult -->
</testsuite> <!-- MyTest -->
